### ISSUE TITLE
Cannot unregister event

### ISSUE THREAD

**Issue by jurepetrovic** [geblanco/electron-router#14]
Hello Gentlemen, 

we're using electron-router in combination with electron and React. 
Received events are used to update some react states and consequently 
UI elements. 

When leaving React page, a certain method componentWillUnmount() gets called, 
where we try to remove listeners in order to avoid React errors about updating unmounted 
component. 

Although removeListener() is correctly called, the event does not seem to de-register. 
Next time when loading the tab, we get double the number of events. PLease look at 
attached photo. 

Do you have any idea about that? 

Thanks, 
Jure 
![image](https://user-images.githubusercontent.com/35005863/87941397-64e9b180-ca9b-11ea-9668-0df4afeda7f6.png)

**Comment by geblanco** [comment]
Hi @jurepetrovic,

I see, it seems clear that event is getting fired twice, is it possible that during the registration you are doing it multiple times? or that the router is not being able to deregister the event with the provided parameters?
Could you provide 1) a MWE so I can test it? 2) the code you use to deregister the event?

Best,

**Comment by jurepetrovic** [comment]
We will prepare you MWE. Meanwhile, code below. Registering events: 

```
// register handler for "SPDone" events
this.refreshStates();

this.router.on("store.data", this.refreshSettings);


```
and then deregistering: 

```
componentWillUnmount() {
        
        this._SinglePlayMounted = false; 
        this.router.removeAllListeners();
        console.log("Unmount events: " + this.router._eventsCount);

        //remove listeners with router.removeListener (evt, handler, ctx)
        for (var event in this.router._events) {
            if (this.router._events[event].constructor === Array ) { // case when there are multiple listeners
                
                for (var listener of this.router._events[event]) {
                    console.log("Removing array: " + event);
                    this.router.removeListener(event, listener.fn, listener.context)
                }

            } else {
                this.router.removeListener(event, this.router._events[event].fn, this.router._events[event].context)
                console.log("Removing object: " + event);
            }

        }

        console.log(this.router);
    }
```

We try first to remove all listeners and then each one separately. 
In the end, this.router._events is empty array. However, next time when 
opening the page, we still get double the events - as you can see in the first post. 

Looking for any idea, that could point us towards the right direction. 

Thanks and Rgds, 
Jure

**Comment by geblanco** [comment]
Hi Jure,

Looking at your code I see several possible causes of error, let me elaborate:
The Router object inherits from EventEmitter, that is why you have a `removeAllListeners` method and `_events` property (maybe those should be masked to avoid confusion?), but those pertain to the EventEmitter object, not the router itself, therefore, when you remove the listener you are doing so in the parent object, so the events are still present both in IPC and Windows.

I think the proper way to remove the listener would be:
```js
this.router.removeListener("store.data", this.refreshSettings)
this.router.clean()
```

Could you try this snippet and post back the result?

Regards,

**Comment by jurepetrovic** [comment]
Ok, thanks, we will try this. Will get back to you. 

This is mwe: 
https://github.com/bad2Dbone/slotsimMWE

But requires you to do yarn install and yarn start.

**Comment by bad2Dbone** [comment]
Hi Geblanco,

I have read the events from router variable and called removeListener before, you can see some commented code in the link, given by Jure. We just didn`t use the .clean function after. 
Well, I have tried it now, but it made no change. 

the commented code:

```
for (var event in this.router._events) {
            if (this.router._events[event].constructor === Array ) { // case when there are multiple listeners
                
                for (var listener of this.router._events[event]) {
                    console.log("Removing array: " + event);
                    this.router.removeListener(event, listener.fn, listener.context)
                }

            } else {
                this.router.removeListener(event, this.router._events[event].fn, this.router._events[event].context)
                console.log("Removing object: " + event);
            }

        }
```

**Comment by geblanco** [comment]
Hi @bad2Dbone!

I have tried your MWE. It seems you have left some git related stuff from a merge in the `package.json` file. After fixing it and installing the dependencies I came across another error when starting the application. Here is the pic:

![error](https://user-images.githubusercontent.com/6652222/88041394-9cfbfd80-cb4a-11ea-9efa-7c9a36d14d9f.png)

I am running under Linux.

**Comment by bad2Dbone** [comment]
> Hi @bad2Dbone!
> 
> I have tried your MWE. It seems you have left some git related stuff from a merge in the `package.json` file. After fixing it and installing the dependencies I came across another error when starting the application. Here is the pic:
> 
> ![error](https://user-images.githubusercontent.com/6652222/88041394-9cfbfd80-cb4a-11ea-9efa-7c9a36d14d9f.png)
> 
> I am running under Linux.

Well, the favicon.ico is there, on gitHub can be even opened, but the app wasn`t build for linux... a lot of it was deleted to make minimal (almost) working example, so there will be dead bodies found all over. If you can`t make it start, do you have an option to try on windows, preferably 10? Maybe exactly the OS causes problems, it wouldn`t be the first one on this project...

**Comment by geblanco** [comment]
Hello @bad2Dbone,

I can open the icon with any image visualizer in Linux, maybe the error is from Electron. I got it working by modifying the `BrowswerWindow` constructor to pass no icon, it is working now.

Also, I have reviewed the whole removeListener process and it was not working... thanks for catching that up!
The process of removing listeners is fixed now, it also includes a `removeAllListeners` method to mask the parent one and effectively remove the ones from IPC too. I have written the tests and they all pass correctly.

But, in the process, your MWE broke. It has to do with some async/await calls you do (in the IPCServer?). As you know, in order to remove a listener from an event emitter, you have to pass the callback, it is okay to pass anonymous/arrow functions if you won't remove the call later, but in the case of async/await there is something else happening. I'm not used to this semantics (I'm into Python now), so it is a bit out my scope. To get a better idea of what is happening, this was the `router.on` code before:

```js
on (evt, listener, ctx) {
  super.on(evt, listener, ctx)
  if (ipc && ipc.on) {
    ipc.on(evt, function (event) {
      let args = Array.prototype.slice.call(arguments, 1)
      DEBUG('on', 'inside ipc on', evt, args)
      listener.apply(ctx, args)
      args = event = null
    })
  }
}
```
And this is the code now:
```js
on (evt, listener, ctx) {
  super.on(evt, listener, ctx)
  if (ipc && ipc.on) {
    ipc.on(evt, listener)
  }
}
```
I had to pass the listener directly in order to be able to remove it later. When using the updated router with your MWE, I get this error:
```
[1] (node:312182) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'section' of undefined
[1]     at IpcMainImpl.<anonymous> (/home/gb/Documents/Dev/slotsimMWE/public/IPCServer.js:86:42)
[1]     at IpcMainImpl.emit (events.js:223:5)
[1]     at WebContents.<anonymous> (electron/js2c/browser_init.js:3911:15)
[1]     at WebContents.emit (events.js:223:5)
[1] (node:312182) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
[1] (node:312182) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
[1] (node:312182) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'section' of undefined
[1]     at IpcMainImpl.<anonymous> (/home/gb/Documents/Dev/slotsimMWE/public/IPCServer.js:86:42)
[1]     at IpcMainImpl.emit (events.js:223:5)
[1]     at WebContents.<anonymous> (electron/js2c/browser_init.js:3911:15)
[1]     at WebContents.emit (events.js:223:5)
[1] (node:312182) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 2)
```

I think we are on the right track, but there is some fine-tuning to do. What are your thoughts on this?

Best,

**Comment by bad2Dbone** [comment]
Hi,

I have copied your changes into `node_modules\electron-router\router.js` of my full project, and got that same error. It happens, because the second argument of `router.send` does not come trough: In General.js there is `this.router.send("store.get", req)` where the `req` variable is defined:
![image](https://user-images.githubusercontent.com/59020138/88143189-15b89380-cbf7-11ea-9e6c-0c5d61de76d9.png)

 On the other side in the IPCServer.js after this line: `router.on("store.get", async (req) => {`, the `req` variable is:
![image](https://user-images.githubusercontent.com/59020138/88143383-6cbe6880-cbf7-11ea-821a-24a594e3839d.png)

I think it has something to do with this line `let args = Array.prototype.slice.call(arguments, 1)`, which is now removed.

**Comment by geblanco** [comment]
Hmm I see, it doesn't happen with the tests. Inspecting it further, when the router emits through event emitter, the event is not an argument, it works normally, but when emitting through ipc the first parameter is always the event.
I'll have to wrap those functions and put them to cache, just like the duplex comm calls, right now I have no bandwidth for this, but I expect to be able to work on this later today or tomorrow, I'll post back when ready!

**Comment by jurepetrovic** [comment]
Hello, 

ok, so we updated the MWE example to try again: 
https://github.com/bad2Dbone/slotsimMWE

-  icon is removed, so it should run for you normally. 

- we added modified router.js file from node_modules. after you do yarn install, please revert to version in the repository. It contains your suggested updates. 

- after you do yarn start, click between tabs (General and SinglePlay). In the browser console, you should see multiple messages each time, meaning event was not properly deregistered. 



Please let us know, if you have any more ideas regarding that. I can also invite you to this repo, so you can commit into it - possible fixes.

![image](https://user-images.githubusercontent.com/35005863/88271704-dada5c80-ccd7-11ea-9c51-1c7642a4794d.png)


Thanks, 
Jure

**Comment by geblanco** [comment]
Hi @jurepetrovic,

I have added the `on` events to cache, now all listeners get called as usual, without the event parameter. I have also corrected the MWE to reflect this changes (see the new commit in the repo).

Thanks for the effort, this was a subtle, but big bug. I expect it to work correctly, please confirm it so we can close the issue. 
I have tested your MWE and seems to work correctly, I left a comment in src/components/General.js with stuff about listeners removal.

Best,

**Comment by jurepetrovic** [comment]
Hey @geblanco, 

thank you very much for the effort! 
We will check it out immediatelly when we get a free minute ;-)

Rgds,
Jure

**Comment by bad2Dbone** [comment]
Hello @geblanco,

I have copied your changes into my whole project... it works!!. Happy like a hippie. 
Tried ` this.router.removeListener(...)` and `this.router.removeAllListeners();` Both statements seem to do the job now. Thank you.

P.S.: when are you planning to update electron-router on NPM to your latest predicted version 0.5.0. ?

**Comment by geblanco** [comment]
Hi @jurepetrovic, @bad2Dbone!

Thank you both for the effort!
It is now publish on npm registry, it is versioned as 0.5.1, please update accordingly.

Closing this now,
Good luck on your endeavour!

**Comment by jurepetrovic** [comment]
Thank you for the help! :-)
